// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function ScanDirectory(arg1:string):Promise<Array<fs.AudioFile>>;

export function SelectDirectory():Promise<string>;
