// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MediaPort() {
  return window['go']['fs']['FsService']['MediaPort']();
}

export function ScanDirectory(arg1) {
  return window['go']['fs']['FsService']['ScanDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['fs']['FsService']['SelectDirectory']();
}
